import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

# Load synthetic data (generated by data/generate_synthetic_data.py)
df = pd.read_csv('../data/synthetic_borehole_data.csv')

# Generate pseudo soft partition probabilities based on layer
# Simulating the output of DEC clustering
def soft_prob(layer):
    if layer < 4:
        return [0.8, 0.15, 0.05]   # Shallow assemblage
    elif layer < 7:
        return [0.2, 0.6, 0.2]     # Middle assemblage
    else:
        return [0.05, 0.15, 0.8]   # Deep assemblage

soft_probs = np.array([soft_prob(l) for l in df['layer']])

# Feature matrix: coordinates + soft probabilities
X = np.column_stack([df['x'], df['y'], soft_probs])
y = df['z_true'].values

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train a simple MLP regressor (lightweight DCNF demonstration)
mlp = MLPRegressor(
    hidden_layer_sizes=(128, 64),
    activation='relu',
    max_iter=500,
    random_state=42,
    early_stopping=True
)
mlp.fit(X_train, y_train)

# Predict and evaluate
y_pred = mlp.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"RMSE on synthetic data: {rmse:.2f} m")